### ISSUE TITLE
Dependances - Failed building wheel for numpy

### ISSUE THREAD

**Issue by mickaelBert** [lelas33/plugin_peugeotcars#13]
Bonjour Lelas, 

Je viens d'essayer d'installer le plugin sur une machine avec cette conf : 
Raspbian : Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
Jeedom : 4.1.28
python -V : Python 2.7.16
**python3 -V : Python 3.7.3**
**pip -V : pip 22.0.4** from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)

Lors de l'installation des dépendances, cela failed avec cette erreur : 
```
ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```

J'ai tenté d'installer numpy et j'ai cette erreur : 

```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy
  Downloading numpy-1.21.5.zip (10.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 2.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [607 lines of output]
 /tmp/pip-install-wiuqm_a_/numpy_b51d1026f471434cb96b2b4a9578337f/tools/cythonize.py:76: **DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.**
        required_version = LooseVersion('0.29.24')
      /tmp/pip-install-wiuqm_a_/numpy_b51d1026f471434cb96b2b4a9578337f/tools/cythonize.py:78: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_common.pyx
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_pcg64.pyx
      Cythonizing sources
      blas_opt_info:
....
```

J'ai tenté pas mal de choses pour réussir à passer numpy mais rien à faire, as tu une idée ?

**Comment by mickaelBert** [comment]
Je viens d'installer numpy sur une version inférieure (1.17.5) avec succès (mais toujours supérieure au requirements de ton fichier requirements.txt ) : 
sudo python3 -m pip install 'numpy>1.17, <1.18' --force-reinstall

J'ai réinstallé les dépendance du plugin ensuite, 
Sur la phase lié à numpy, il detect qu'il est bien présent maintenant. 
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from matplotlib->androguard->-r /var/www/html/plugins/peugeotcars/core/class/../../resources/../3rdparty/psa_jeedom_daemon/requirements.txt (line 8)) (1.17.5)

et l'installation des dépendances se termine entièrement. 

N'hésites pas si tu as besoin d'info complémentaires.

**Comment by lelas33** [comment]
Bonsoir,
Merci pour ces infos. Bonne idée de revenir sur une version plus ancienne de numpy

En fait, il n'y a pas de version min imposée dans le fichier requirements.txt, car numpy est installé en dépendance de la librairie androguard, et je suppose donc que le choix des versions est fait au moment de l'installation selon le contexte.
Tu dois avoir un jeu de version différents de ceux utilisés jusqu'à présent.

Dans mon install, sur serveur Linux Ubuntu, j'ai 
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from matplotlib->androguard->-r /var/www/html/plugins/peugeotcars/core/class/../../resources/../3rdparty/psa_jeedom_daemon/requirements.txt (line 7)) (1.20.1)

**Comment by mickaelBert** [comment]
Effectivement, j'ai vu pas mal de souci avec ce nouveau Numpy sur certains config. Ça servira peut être pour d'autres personnes :) 
Merci pour ce plugin, je m'empresse de le tester :) 
Bonne journée,

**Comment by ZeiTounE** [comment]
Bonjour @lelas33 

Je voulais tester ton plugin sur une peugeot e208, mais j'ai des soucis dans l'initialisation.
Il ne semble pas y a voir de soucis dans l'installation des dépendances (au 1er lancement j'ai eu des erreurs que j'ai corrigé à la main), et depuis je ne reçois pas le SMS  et la configuration ne se termine pas correctement.

Ci joint le log de l'installation des dépendances, si tu peux m'aider ...
Merci pour le temps passé.

[peugeotcars_update.log](https://github.com/lelas33/plugin_peugeotcars/files/9964009/peugeotcars_update.log)

**Comment by lelas33** [comment]
Bonjour @ZeiTounE ,

Je te propose d'ouvrir une nouvelle issue pour ce post. Il est difficile à trouver dans une issue fermée.
Il y a bien en effet une erreur sur le step 5 de l'installation. Je pense qu'il y a eu des évolutions dans l'appli sur la gestion des certificats. J'ai vu que Flobz avait fait une mise à jour de son coté, il faut que je mette à jour également dans ce plugin.
Je te dirai quand ce sera fait.

Lelas

**Comment by ZeiTounE** [comment]
Salut Lelas,

Pas de soucis pour ouvrir un nouvel issue, mais je pense que tu peux te basé sur celui ci :

Issue https://github.com/lelas33/plugin_peugeotcars/issues/15

Encore merci pour le temps que cela va te pendre.
ZeitounE
