### ISSUE TITLE
Parametre altitude coordonnées gps

### ISSUE THREAD

**Issue by djsyl** [lelas33/plugin_peugeotcars#3]
Au début on avait dans les coordonnées GPS le parametre correspondant a l'altitude 
(vue aussi dans le log.gps)
depuis les dernières maj celui-ci est a 0 

1609323003,48.729343,2.5092647,>>104<<,100,162.2,0
1609323204,48.729343,2.5092647,>>0<<,100,162.2,0

???

**Comment by lelas33** [comment]
Bonne remarque.
J'avais ajouté une vérification sur la présence de ce 3eme champ, car il n'est pas toujours présent. Mais j'avais une erreur dans le check. Je corrige.
D'ailleurs, je n'avais pas réalisé que c'était l'altitude. Je pensais que c'était la direction de la voiture, mais la valeur me paraissait étrange. 
Merci pour ce retour.

**Comment by djsyl** [comment]
Il est possible que cette valeur ne soit pas toujours présente du au fonctionnement des gps
lorsqu'il n'y a pas assez de satellite le résultat est en 2D si assez ça passe en 3D avec altitude
