### ISSUE TITLE
API connection error

### ISSUE THREAD

**Issue by TiphTech** [lelas33/plugin_peugeotcars#4]
Date et heure | Source | Description
 -- | -- | -- | 
   2021-02-11 05:50:05 | peugeotcars | Erreur Login API PSA

Quelques soucis de connection à l'API depuis quelques jours, plus de remontée d'infos, l'URL à changée?

**Comment by lelas33** [comment]
Pas de soucis particulier de mon coté. J'ai des remontées d'info correctes.
L'URL n'a pas changé.
Cela m'arrive quelques fois, d'avoir ce message, mais pas en continu.
Tu n'as plus aucune remontée depuis plusieurs jours ?

**Comment by TiphTech** [comment]
C'est bon tout re fonctionne, ces jours je n'arrivais plus à rafraichir mes données (depuis le plugin et depuis l'application) pendant quelques heures je n'avais plus de remontées d'info, maintenant le refresh se refait bien, peut-être trop de requêtes envoyé au serveurs psa (j'ai un script qui en envoi en plus du plugin)
Merci!

**Comment by lelas33** [comment]
Bonne nouvelle.
Il y a effectivement une limite en nombre de requête par jour.
Flobz qui travaille également sur cette API, avait vérifié qu'il ne fallait pas dépasser un requête toute les 2 minutes
J'ai calé mon plugin à une requête toute les 5 mn, et toute les minutes lors du déplacement du véhicule

**Comment by TiphTech** [comment]
D’accord! Intéressant, oui justement j’ai son script qui envoi toutes les 2min, plus le tiens ça faisait trop je crois
